# Copyright (c) https://github.com/UWU-TEAM 2025-present
# Copyright (c) https://github.com/linastorvaldz 2025-present

name: "🦊 Orangefox Recovery Builder"
description: "Build OrangeFox Recovery with Github Action"
author: "linastorvaldz"

branding:
  icon: 'terminal'
  color: 'yellow'

inputs:
  FOX_SYNC_BRANCH:
    description: 'Manifest Branch'
    type: string
    default: '12.1'
  USER_NAME:
    description: 'Your GitHub username'
    type: string
  USER_EMAIL:
    description: 'Your GitHub email'
    type: string
  KERNEL_TREE:
    description: 'Your device kernel tree'
    type: string
  KERNEL_BRANCH:
    description: 'Kernel tree branch'
    type: string
  KERNEL_PATH:
    description: 'Path to kernel directory'
    type: string
  DEVICE_TREE:
    description: 'Device tree repository'
    type: string
  DEVICE_TREE_BRANCH:
    description: 'Device tree branch'
    type: string
  DEVICE_PATH:
    description: 'Path to device tree'
    type: string
  DEVICE_NAME:
    description: 'Specify your device codename'
    type: string
  BUILD_TARGET:
    description: 'Specify Your Build Target [boot,recovery,vendorboot]'
    type: string
  COMMON_TREE:
    description: 'Your device common tree (if exists)'
    type: string
  COMMON_BRANCH:
    description: 'Your device common tree branch'
    type: string
  COMMON_PATH:
    description: 'Path to your common device tree'
    type: string
  MAINTAINER_URL:
    description: 'Image size must be 192x192'
    type: string
  TG_CHAT_ID:
    description: 'Telegram Chat ID'
    type: string
  TG_TOKEN:
    description: 'Telegram Bot Token'
    type: string
  TIMEZONE:
    description: 'Specify Your Timezone'
    type: string
    default: 'Asia/Makassar'

runs:
  using: 'composite'
  steps:

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set swap space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Set GitHub Path
      shell: bash
      run: |
        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Prepare Build Environment
      shell: bash
      run: |
        sudo apt-get install -y aria2
        git clone --depth=1 https://gitlab.com/OrangeFox/misc/scripts.git -b master .sc
        sudo bash .sc/setup/android_build_env.sh
        sleep 1
        sudo timedatectl set-timezone "${{ inputs.TIMEZONE }}"

    - name: Sync OrangeFox Manifest
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        mkdir -p ${GITHUB_ACTION_PATH}/OrangeFox
        cd ${GITHUB_ACTION_PATH}/OrangeFox
        git config --global user.name "${{ inputs.USER_NAME }}"
        git config --global user.email "${{ inputs.USER_EMAIL }}"

        git clone --depth=1 https://gitlab.com/OrangeFox/sync.git
        cd sync
        ./orangefox_sync.sh \
        --branch ${{ inputs.FOX_SYNC_BRANCH }} \
        --path ${GITHUB_ACTION_PATH}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
        cd -

        cd ${GITHUB_ACTION_PATH}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
        if [[ ! -d bootable/recovery/gui/theme ]]; then
            git clone --depth=1 \
            https://gitlab.com/OrangeFox/misc/theme.git \
            bootable/recovery/gui/theme
        fi
        if [[ ! -d external/nano ]]; then
            git clone --depth=1 \
            https://github.com/LineageOS/android_external_nano \
            -b lineage-19.1 \
            external/nano
        fi
        if [[ ! -d external/libncurses ]]; then
            git clone --depth=1 \
            https://github.com/LineageOS/android_external_libncurses \
            -b lineage-19.1 \
            external/libncurses
        fi
        if [[ ! -d external/bash ]]; then
            git clone --depth=1 \
            https://github.com/LineageOS/android_external_bash \
            -b lineage-19.1 \
            external/bash
        fi
        if [[ ! -d external/lptools ]]; then
            git clone --depth=1 \
            https://github.com/phhusson/vendor_lptools \
            external/lptools
        fi
        if [[ -n "${{ inputs.MAINTAINER_URL }}" ]]; then
            wget -q ${{ inputs.MAINTAINER_URL }} -O ${GITHUB_ACTION_PATH}/maintainer.png
            cp -r ${GITHUB_ACTION_PATH}/maintainer.png bootable/recovery/gui/theme/portrait_hdpi/images/Default/About
        fi
        if [[ -n "${{ inputs.KERNEL_TREE }}" ]]; then
            git clone --depth=1 \
            ${{ inputs.KERNEL_TREE }} \
            -b ${{ inputs.KERNEL_BRANCH }} \
            ${{ inputs.KERNEL_PATH }}
        fi
        if [[ -n "${{ inputs.COMMON_TREE }}" ]]; then
            git clone --depth=1 \
            ${{ inputs.COMMON_TREE }} \
            -b ${{ inputs.COMMON_BRANCH }} \
            ${{ inputs.COMMON_PATH }}
        fi
        if [[ -n "${{ inputs.DEVICE_TREE }}" ]]; then
            git clone --depth=1 \
            ${{ inputs.DEVICE_TREE }} \
            -b ${{ inputs.DEVICE_TREE_BRANCH }} \
            ${{ inputs.DEVICE_PATH }}
        fi

    - name: 🦊 Build OrangeFox Recovery
      shell: bash
      env:
        TG_CHAT_ID: ${{ inputs.TG_CHAT_ID }}
        TG_TOKEN: ${{ inputs.TG_TOKEN }}
        FOX_BRANCH: ${{ inputs.FOX_SYNC_BRANCH }}
        CODENAME: ${{ inputs.DEVICE_NAME }}
        DEVICE_PATH: ${{ inputs.DEVICE_PATH }}
        BUILD_TARGET: ${{ inputs.BUILD_TARGET }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        source functions.sh
        timeStart

        cd ${GITHUB_ACTION_PATH}/OrangeFox/fox_${FOX_BRANCH}
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true

        export BUILDLOG=$(realpath ./build.log)
        export OUT=$(realpath ./out/target/product/$CODENAME)
        export DEVICE=$(grep "PRODUCT_MODEL :=" ./$DEVICE_PATH/twrp_$CODENAME.mk -m 1 | cut -d = -f 2)

        lunch twrp_$CODENAME-eng
        sleep 5
        build_message "Building... 🛠️"
        mka adbd ${BUILD_TARGET}image -j$(nproc --all) 2>&1 | tee -a ${BUILDLOG}
        export retVal=${PIPESTATUS[0]}
        timeEnd
        buildStatus

        export ORF_IMG_SHA1=$(sha1sum $OUT/OrangeFox*.img | cut -d ' ' -f1)
        export ORF_ZIP_SHA1=$(sha1sum $OUT/OrangeFox*.zip | cut -d ' ' -f1)
        export ORF_ZIP_NAME=$(basename $OUT/OrangeFox*.zip)
        export ORF_IMG_NAME=$(basename $OUT/OrangeFox*.img)
        export ORF_GHREPO="https://github.com/${{ github.repository }}"
        export ORF_LINK="${ORF_GHREPO}/releases/tag/${BUILD_DATE}"

        sleep 2
        ORF_FILES=$(echo $OUT/{OrangeFox*.zip,OrangeFox*.img})
        echo "ORF_FILES: $ORF_FILES"
        sed -i "s/ZIP_NAME/${ORF_ZIP_NAME}/g" notes.sh
        sed -i "s/IMG_NAME/${ORF_IMG_NAME}/g" notes.sh
        bash notes.sh
        gh release create \
            "$BUILD_DATE" \
            "$ORF_FILES" \
            --title "🦊 OFRP for ${DEVICE} (${CODENAME}) // ${BUILD_DATE}" \
            -F "${GITHUB_ACTION_PATH}/release-notes.md" \
            -R "${{ github.repository }}"
        sleep 1
        build_success_msg "$ORF_LINK"
