# Copyright (c) https://github.com/UWU-TEAM 2025-present
# Copyright (c) https://github.com/linastorvaldz 2025-present

name: "ðŸ¦Š Orangefox Recovery Builder"
description: "Build OrangeFox Recovery with Github Action"
author: "linastorvaldz"

branding:
  icon: 'terminal'
  color: 'yellow'

inputs:
  FOX_SYNC_BRANCH:
    description: 'Manifest Branch'
    type: string
    default: '12.1'
  DEVICE_TREE:
    description: 'Device tree repository'
    type: string
  DEVICE_TREE_BRANCH:
    description: 'Device tree branch'
    type: string
  DEVICE_PATH:
    description: 'Path to device tree'
    type: string
  DEVICE_NAME:
    description: 'Specify your device codename'
    type: string
  BUILD_TARGET:
    description: 'Specify Your Build Target [boot,recovery,vendorboot]'
    type: string
  TG_CHAT_ID:
    description: 'Telegram Chat ID'
    type: string
  TG_TOKEN:
    description: 'Telegram Bot Token'
    type: string
  TIMEZONE:
    description: 'Specify Your Timezone'
    type: string
    default: 'Asia/Makassar'

runs:
  using: 'composite'
  steps:
    - name: Cleanup
      uses: mehyaa/slimhub_actions@fix/toolset-url

    - name: Set swap space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Set GitHub Path
      shell: bash
      run: |
        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Prepare Build Environment
      shell: bash
      run: |
        git clone --depth=1 https://github.com/akhilnarang/scripts.git -b master .sc
        sudo bash .sc/setup/android_build_env.sh
        sleep 1
        sudo timedatectl set-timezone "${{ inputs.TIMEZONE }}"

    - name: Sync OrangeFox Manifest
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        mkdir -p ${GITHUB_ACTION_PATH}/OrangeFox
        cd ${GITHUB_ACTION_PATH}/OrangeFox
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

        git clone --depth=1 https://gitlab.com/OrangeFox/sync.git
        cd sync
        ./orangefox_sync.sh \
        --branch ${{ inputs.FOX_SYNC_BRANCH }} \
        --path ${GITHUB_ACTION_PATH}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
        cd -

        cd ${GITHUB_ACTION_PATH}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
        git clone --depth=1 \
            ${{ inputs.DEVICE_TREE }} \
            -b ${{ inputs.DEVICE_TREE_BRANCH }} \
            ${{ inputs.DEVICE_PATH }}
        
        cd ${{ inputs.DEVICE_PATH }}
        echo "DT_BRANCH=$(git branch --show-current)" >>$GITHUB_ENV
        cd -

    - name: ðŸ¦Š Build OrangeFox Recovery
      shell: bash
      env:
        TG_CHAT_ID: ${{ inputs.TG_CHAT_ID }}
        TG_TOKEN: ${{ inputs.TG_TOKEN }}
        FOX_BRANCH: ${{ inputs.FOX_SYNC_BRANCH }}
        CODENAME: ${{ inputs.DEVICE_NAME }}
        DEVICE_PATH: ${{ inputs.DEVICE_PATH }}
        BUILD_TARGET: ${{ inputs.BUILD_TARGET }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        source functions.sh
        timeStart

        cd ${GITHUB_ACTION_PATH}/OrangeFox/fox_${FOX_BRANCH}
        set +e
        source build/envsetup.sh
        set -e

        export BUILDLOG=$(realpath ./build.log)
        export OUT=$(realpath ./out/target/product/$CODENAME)
        export DEVICE=$(grep "PRODUCT_MODEL :=" ./$DEVICE_PATH/twrp_$CODENAME.mk -m 1 | cut -d = -f 2)

        lunch twrp_$CODENAME-eng
        sleep 5
        build_message "Building... ðŸ› ï¸"
        mka ${BUILD_TARGET}image -j$(nproc --all) 2>&1 | tee -a ${BUILDLOG}
        export retVal=${PIPESTATUS[0]}
        timeEnd
        buildStatus

        export ORF_GHREPO="https://github.com/${{ github.repository }}"
        export ORF_LINK="${ORF_GHREPO}/releases/tag/${BUILD_DATE}"
        
        sleep 2
        ORF_FILES=$(echo $OUT/{OrangeFox*.zip,OrangeFox*.img})
        create_release_notes
        gh release create \
            "$BUILD_DATE" \
            $ORF_FILES \
            --title "ðŸ¦Š OFRP for ${DEVICE} (${CODENAME}) // ${BUILD_DATE}" \
            -F "${GITHUB_ACTION_PATH}/release-notes.md" \
            -R "${{ github.repository }}"
        sleep 1
        build_success_msg

